# Generated by Django 5.2.3 on 2026-03-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produit_cout_moyen_pondere_achat_achatitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='barcode',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
