# Generated by Django 5.2.3 on 2026-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='est_paye',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
