# Generated by Django 5.2.6 on 2026-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_vente_est_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
