# Generated by Django 5.2.6 on 2026-03-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_vente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmée', 'Confirmée'), ('annulée', 'Annulée')], default='brouillon', max_length=20),
        ),
    ]
