# Generated by Django 5.2.3 on 2026-03-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_vente_remise_and_remove_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='montant_tva',
        ),
    ]
