# Generated by Django 5.2.3 on 2026-03-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_montant_tva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='type_remise',
        ),
        migrations.AddField(
            model_name='venteitem',
            name='type_remise',
            field=models.CharField(choices=[('gros', 'Gros (-30%)'), ('semi-gros', 'Semi-gros (-10%)'), ('détails', 'Détails (0%)')], default='détails', max_length=20),
        ),
    ]
